# ¡No necesitas apt-get install nada!
FROM python:3.10-slim

WORKDIR /app

# Copiar dependencias y luego instalar (mejor para cache)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto del código
COPY . .

EXPOSE 50010

CMD ["python", "main.py"]
