apiversion: v1
kind: Secret
metadata:
  name: gitlab-registry
  namespace: clipExtract-backend
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoiYWxlamFuZHJvZ2FwZTA1QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiQ0lfSk9CX1RPS0VOIn19fQ==
# ---------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: clipExtract-backend
type: Opaque
data:
  password: YWRtaW4=

