apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry
  namespace: clipextract-backend
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoiYWwzeHBsYXl0IiwicGFzc3dvcmQiOiJnbHBhdC1jMUI5d1RfWEh3c3k5Z1N0UDNDbiIsImVtYWlsIjoiYWxlamFuZHJvZ2FwZTA1QGdtYWlsLmNvbSIsImF1dGgiOiJZV3d6ZUhCc1lYbDBPbWRzY0dGMExXTXhRamwzVkY5WVNIZHplVGxuVTNSUU0wTnUifX19