apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry
  namespace: clipextract-backend
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoiYWxlamFuZHJvZ2FwZTA1QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiQ0lfSk9CX1RPS0VOIn19fQ==