apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry
  namespace: clipextract-backend
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoiYWwzeHBsYXl0IiwicGFzc3dvcmQiOiJnbGZ0LWc4Tm5LV3plR3h3eld2VEF6amFDIiwiZW1haWwiOiJhbGVqYW5kcm9nYXBlMDVAZ21haWwuY29tIiwiYXV0aCI6IllXd3plSEJzWVhsME9tZHNablF0WnpoT2JrdFhlbVZIZUhkNlYzWlVRWHBxWVVNPSJ9fX0=