apiVersion: v1
kind: Service
metadata:
  name: svc-backend
  namespace: clipextract-backend
spec:
  selector:
    app: clipextract-backend
  ports:
    - protocol: TCP
      port: 50010
      targetPort: 50010
  type: ClusterIP