apiVersion: v1
kind: service
metadata:
  name: svc-backend
  namespace: clipExtract-backend
spec:
  selector:
    app: clipextract-backend
  ports:
    - protocol: TCP
      port: 50010
      targetPort: 50010
  type: ClusterIP