apiVersion: v1
kind: Service
metadata:
  name: svc-postgresql
  namespace: clipextract-backend
spec:
  selector:
    app: clipextract-backend
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  # The PostgreSQL service is typically exposed on port 5432
  type: ClusterIP
